[workspace]
authors = ["Ilya Lubenets <xfilinxcl@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "AOC2025"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025120605,<0.27"
